### ISSUE TITLE
Proxying with nginx seems to work only using https

### ISSUE THREAD

**Issue by tfinke** [novnc/noVNC#1020]
Dear NoVNC Team,

first of all: great project!

We have tried to reverse proxy a session through a firewall using the http protocol. We did this based on the very useful description on https://github.com/novnc/noVNC/wiki/Proxying-with-nginx. But it seems that nginx refuses to upgrade to the ws protocol when no Connection or no Upgrade header entry is present. These very header entries are defined as hop-by-hop (RFC 2616, p. 91) and thus could have been removed by any proxy in between. Newer versions of Nginx seem not to add these entries if they are missing. That explains why connections could fail using http. 

On the other hand all works great using https, because no proxy in between can remove these headers. So - if I am right - I would suggest to add this information to the proxying-page mentioned above and to modify the configuration using port 443 instead of port 80. Also it could be useful to link to the docs for Nginx TLS termination (https://www.nginx.com/resources/admin-guide/nginx-ssl-termination/). The server section then should look like:

    server {
        listen                443 ssl;
        server_name           www...;
        ssl_certificate       /etc/...;
        ssl_certificate_key   /etc/...;

Hopefully this was useful.
Thanks again for your phantastic project and best regards

tfinke

**Comment by DirectXMan12** [comment]
That sounds like a good recommendation.  You should be able to make the edit to the wiki yourself, actually.

**Comment by samhed** [comment]
Thanks for adding it to the wiki @tfinke

**Comment by larryathey** [comment]
I realize this is an old thread, but is there any reason that Nginx can't do this without the need for websocketproxy.py ??

The reason I ask is because I have a Linux VM that is used for a reverse SSH tunnel host and I already have about 150 computers reverse tunneling their VNC server to it where each machine starts at localhost:30000

So is websocketproxy.py really necessary if I already have Nginx installed and running on it?
