### ISSUE TITLE
Tight PNG encoding broken

### ISSUE THREAD

**Issue by CendioOssman** [novnc/noVNC#1027]
It got broken in the cleanup in 3e8b26ab58e7ef7457a324304306981d1ab0f528. The Tight PNG extension is a bit redundant in that it uses both a new encoding number, and a new Tight filter number. The cleanup assumed it was just a filter and not both.

@kanaka, feel like writing an official spec for @rfbproto? ;)

#1026 is supposed to fix this.

**Comment by kanaka** [comment]
@CendioOssman so should I define it as an encoding or pseudo-encoding? It's in the negative number range for pseodo-encodings (-260). If I recall, the reason for this is because it originally borrowed from QEMU's pseudo-encoding range. However, it functions more like a regular encoding (variant of tight). Apart from convention, is there any standard/documentation that pseudo-encodings are negative and regular encodings are not?

**Comment by CendioOssman** [comment]
Merged the fix to noVNC. Protocol update is handled as rfbproto/rfbproto#11.
