### ISSUE TITLE
Is It Possible to Stay Anonymous When Using noVNC?

### ISSUE THREAD

**Issue by JohnMcKinsey** [novnc/noVNC#1053]
Hello,

My question is rather straightforward: Is it possible to remain fully anonymous when using noVNC to log in to a VPS server?

The VPS provider offers mainly two options to connect to the VPS: 

1. RDP
2. VNC

I have heard of the security risks of using the RDP protocol to log in, for example:

The screen size, the version of the operating system, some licensing details, version of the client, IP address, etc. are sent to the RDP server when the client establishes the connection. Now the IP address can be anonymized using, for example, Tor, or VPN. One can simply switch on the VPN client with a lock feature enabled which forbids any outbound traffic that would try to send packets outside of the VPN tunnel.

In that case, when the client logs into the VPS, the IP address of the Tor exit node, or of the VPS server, would be seen in the logs of the operating system (Windows) that received the RDP connection. So that is fine (this does not help identify the client), however, all of these other pieces of identifying information would be sent along with the IP address (which is bad from an anonymity point of view).

Since noVNC can be used from within a web browser (and that includes the Tor browser, which anonymizes the traffic), I think from the IP address standpoint, one can really be anonymous when logging into the VPS server. 

So I think my question boils down to:

Is VNC better in terms of anonymity and security than RDP? Does the fact that VNC is used from within an anonymized web browser make VNC better than RDP? Is no such information such as the version of the operating system, licensing info, screen size, or any of these other pieces of information, that could potentially create a unique "fingerprint" of the client, logged anywhere when the client logs in via VNC (or noVNC to be more specific)?

My gut level feeling tells me that VNC is safer, because not only the IP address, but also other things like the version of the OS, screen size, etc., can be anonymized when using a web browser (for example, via user agent spoofing). As a good example, the Tor browser does that by default (creates a window of optimal dimensions so that the user of the browser is no different from many of the other users paranoid about their online security, which helps anonymity). The Tor browser, on top of that, also spoofs the user agent, and has some other nice security features.

**Comment by kanaka** [comment]
Short answer: RDP (VNC) sends less identifying info than RDP, but remote frame buffer protocols in general are probably not a good way to stay anonymous.

I'm not intimately familiar with the RDP protocol. A VNC client does send the version of the RFB protocol it supports, and security types and render encodings that it supports. Those tend to be fairly generic. From the initial handshake, somebody might be able to tell you are running noVNC and maybe which major version of noVNC but probably not much more. So there is less identifying information in the initial RFB handshake than there is for RDP.

However, note that any sort of remote frame buffer protocol is problematic if you are trying to remain anonymous because mouse movements and keyboard typing are sent to the remote server. It has been demonstrated that this sort of information provides a fairly unique user fingerprint: each person uses the mouse differently, uses a specific timing pattern when typing and tends to make certain typos over and over. I'm also not intimately familiar with the Tor browser and whether it attempts to limit fingerprinting via mouse movement and keyboard typing patterns. Even if it has mechanisms to limit that sort of fingerprinting, I wouldn't count on it working particularly well unless it adds so much latency to mouse and keyboard events that it would be noticeable and annoying.

So it's probably better that RDP. And probably better than a regular VNC client (since the browser inherently adds some jitter and latency to user input), but probably still not that great. If anonymity is critical for you, I wouldn't use a remote frame buffer system at all. Note, that I could see creating a variant of noVNC that modifies what is being sent. For example, only sends mouse clicks and not mouse movement and only sends key events on quarter second boundaries. But I'm not an expert on staying anonymous online so that just me thinking out loud.

**Comment by JohnMcKinsey** [comment]
@kanaka Thank you, this is a really helpful response, indeed.

The info, which is sent when the initial VNC handshake is established, which you have mentioned, like the version of the RFB protocol, etc., seems safe for me. I cannot imagine it revealing the true identity of the person making the connection if VNC is used within the Tor browser (which was created with anonymity as a top priority and even secret agencies like the NSA have real trouble deanonymizing its users). 

So my thinking is that one user will be no different from any other user of the VPS provider, given the user uses VNC to log into the VPS server (in terms of this "underlying" information that is sent to the server, such as the RFB protocol version).

Also, what you have mentioned makes sense (that mouse movements and key presses can create a unique fingerprint of a user), but again, I cannot imagine this serving any true purpose at all, even if, for any reason, one of the top secret agencies like the NSA were after the user. What they would see is how the user uses the mouse and keyboard, but how would they utilize this information in identifying the user? Do they know how every person on the planet uses their mice and keyboards so that they can match them together?

In my lay view, it resembles a scenario in which the police gets the fingerprints of a suspect from a crime scene, but since they do not have the fingerprints of every person on the planet in their database, the fingerprints they got do not match anyone in the database, so they are of no use.

I am open to hearing what others can share and how they can contribute to this discussion.

Thanks again for the insightful answer!

**Comment by samhed** [comment]
noVNC will log to the browser console, that log includes RFB protocol version if log-level is set to INFO or higher. On the server-side you will have logs from your VNC server (which of course differs depending on which server you use) and connection logs from Websockify if you use that. As far as user-actions go, that's nothing the RFB protocol is aware of..

We can't really answer for the server side of things.. since noVNC is only a client.

**Comment by JohnMcKinsey** [comment]
@samhed Thank you, this explains things.

And probably the last thing that I wanted to ask but forgot to do so in my last message:

Does noVNC (or VNC in general) support redirection? For example, in the case of RDP, a client can redirect the sounds from his/her microphone, web camera, his/her own desktop, printers, etc., to the server. This would break anonymity, thus my question.

So is any such sort of redirection possible with VNC or noVNC, and if it is, is it off by default?

**Comment by samhed** [comment]
Nope, it's not included in the RFB protocol (VNC) and not possible with noVNC.

**Comment by kanaka** [comment]
@JohnMcKinsey Again, I'm not an expert, but my understanding is that a common way that people who use anonymization tools have been unmasked is that they are fingerprinted while using those tools and this is later correlated with logs/records/fingerprinting when they access the Internet without those tools (which is probably inevitable regardless of how diligent a person is). So if you must use a remote frame buffer service, then noVNC (on Tor) is probably better than regular VNC is better than RDP. But using a frame buffer service (regardless of whether noVNC and/or Tor) still increases your fingerprint IMO.
