### ISSUE TITLE
Replacement for updatestate callback in noVNC

### ISSUE THREAD

**Issue by jeffforbes** [novnc/noVNC#1114]
In the previous version of noVNC we made extensive use the updatestate function.
We use multiple canvases that are stacked and only show one at a time. We appended the ID of the
canvas to the rfb object that controls the vnc on that canvas. When different states occur we can tell which VM that creates the VNC content had a change in its vnc state. We also used the get_element methods that were defined in the properties.js file, which is no longer used.

In the new vnc_lite.html demo, the event listeners don't have any information (as far as I can tell) about which rfb created the event.

Ant suggestions on how to get this functionality in the noVNC 1.0?

**Comment by CendioOssman** [comment]
`updatestate` has been replaced by the `connect`, and `disconnect` events so you should be able to do the exact same thing there. The rfb object is included as `this`, just like regular DOM events. And you can always bind any extra stuff you need.

(and again, `properties.js` is not something in noVNC so that must be a local modification)
