### ISSUE TITLE
Bandwith size 

### ISSUE THREAD

**Issue by omertombul** [novnc/noVNC#1146]
Hi , I would like to know is there a way to choose the bandwidth size like in UltraVnc.
For ex : LAN(> 1Mbit/s) -Max Colors
              MEDIUM (128 - 256Kbit/s) -256 Colors
             ......
If not what is the default bandwidth used by noVnc.

Thank You

**Comment by samhed** [comment]
No, I'm afraid there is no such setting in noVNC.

And with regards to the default bandwidth used, it's very difficult to say since it depends so much on what you are doing in the remote session.

However, I would guess that the compression level and jpeg quality used by noVNC are probably close to "medium" settings as displayed by other VNC clients.
