### ISSUE TITLE
Using onmousebutton stops propagation to the VM

### ISSUE THREAD

**Issue by dvd900** [novnc/noVNC#1183]
**Describe the bug**
Setting a function on rfb._mouse.onmousebutton stops the VM from recieving clicks

**To Reproduce**
Try to bind a function like, 
`rfb._mouse.onmousebutton = function(x,y,down,bmask){
          logger.log('got mouse down');
}`

I get a log, with the right x and y values but I dont get a click on my VM.
**Expected behavior**
I would expect the mouse clicks to behave the same way, listener or not.

**Client (please complete the following information):**
 - OS: OSX
 - Browser: Chrome Latest

**Comment by samhed** [comment]
This is expected behavior. The code path is like this:

1. mouse events are registered in the constructor for Mouse:
  https://github.com/novnc/noVNC/blob/77e261dba3ac942577e4fe9617340a39df42b6d6/core/input/mouse.js#L29

2. _handleMouseDown calls _handleMouseButton in core/input/mouse.js:
  https://github.com/novnc/noVNC/blob/77e261dba3ac942577e4fe9617340a39df42b6d6/core/input/mouse.js#L104

3. _handleMouseButton in core/input/mouse.js calls Mouse.onmousebutton:
  https://github.com/novnc/noVNC/blob/77e261dba3ac942577e4fe9617340a39df42b6d6/core/input/mouse.js#L99

4. Mouse.onmousebutton is set to RFB._handleMouseButton in the constructor for RFB:
  https://github.com/novnc/noVNC/blob/77e261dba3ac942577e4fe9617340a39df42b6d6/core/rfb.js#L180

5. Your code has overwritten that handler.

**Comment by dvd900** [comment]
Aahh, that's my mistake. Would we be interested in having a way to listen to events happening on the RFB? Going to need to extend my own instance of the library to do so.

**Comment by samhed** [comment]
That could perhaps be interesting. Could you describe your use case a bit?

**Comment by dvd900** [comment]
In the case of slow vm's I want to render an animation on an overlay when a user clicks or drags. You see similar behavior on AWS's device farm.
