### ISSUE TITLE
multi host service

### ISSUE THREAD

**Issue by TerryBradford** [novnc/noVNC#1184]
I wonder if the host service can be configured to access more than just a single host. 

I would like for the service to be able to relay for example : 

I web on to my linux box to vnc to a host client, I select the name or ip of the client and then click on connect. 

presently it appears I can only vnc to the host declared in the launch.sh - I have over 500 devices that I might wish to vnc to and having a variable such as host=12345 would make this a very scalable solution rather than delivering a 1to1 setup. - I might have just got some config wrong manybe ?

**Comment by CendioOssman** [comment]
noVNC in itself doesn't support this. The reason is that we can't (generally) connect directly to a VNC server, but most go through a proxy. So it's up to that proxy to handle any multiplexing between multiple hosts.

websockify (that launch.sh starts) does have some basic support for this via its "token" system. Have a look at this wiki page:

https://github.com/novnc/websockify/wiki/Token-based-target-selection

Do note though that websockify is just a simple server for testing and development and might not be enough for production deployments.
