### ISSUE TITLE
The implemented fence protocol behaviour is not in sync with the actual spec

### ISSUE THREAD

**Issue by mykola-mokhnach** [novnc/noVNC#1217]
The [RFB protocol spec](https://github.com/rfbproto/rfbproto/blob/master/rfbproto.rst#enablecontinuousupdates) says that it's the client's responsibility to request continuous updates from the server by sending the `EnableContinuousUpdates` message. The fact that the server supports this extension could be checked as a part if Tight Security Type authentication.

Although, the current implementation of Fence in noVNC assumes that it has to get the `EnableContinuousUpdates` from the server [first](https://github.com/novnc/noVNC/blob/9a823732a01af080357669d12d355cdc8e7e099c/core/rfb.js#L1416) in order to enable continuous updates on the client side. Is that a bug or the spec is wrong?

**Comment by samhed** [comment]
Hi,

Good eye, thanks for the report!

Yeah, you mean that noVNC waits for `EndOfContinousUpdates` message first, that's true. It's not a bug, we even have [tests](https://github.com/novnc/noVNC/blob/master/tests/test.rfb.js#L2197) verifying that this is the case.

I believe that the spec is wrong in the section you linked. Because [this section in the spec](https://github.com/rfbproto/rfbproto/blob/master/rfbproto.rst#7716continuousupdates-pseudo-encoding) says differently. We should try to get that clarified in the protocol spec.

**Comment by samhed** [comment]
I made an issue for the RFB protocol: https://github.com/rfbproto/rfbproto/issues/20
