### ISSUE TITLE
Optimize for high latency connection

### ISSUE THREAD

**Issue by Ekstazi** [novnc/noVNC#1261]
When server doesn't support fence and continuous updates, novnc has low performance in high latency network.

This can be solved by trying to emulate server push fb update strategy. 
More details described in this document: http://cseweb.ucsd.edu/~pasquale/Papers/globecom10t.pdf

The key idea is send fb update req every 50ms. So server receive it continously without loop between server's fbupdate and client fbupdatereq. This is normally because protocol allow multiple fbupdatereq. And only when server has updates in fb it send fbupdate back to client

**Comment by samhed** [comment]
Thanks for the tip!

Generally when you find something that could be useful for other users you should consider adding it to the wiki. :)

**Comment by Ekstazi** [comment]
May be implement this in novnc ? And also add this doc to wiki

**Comment by samhed** [comment]
My bad, I read your first text too quickly. I misread it as a server-side configuration/modification.

The protocol does indeed indicate that the client should be able to send multiple fb update reqs: https://github.com/rfbproto/rfbproto/blob/master/rfbproto.rst#framebufferupdaterequest

Do you have an example of another VNC client/viewer that works like this?

**Comment by Ekstazi** [comment]
I patched novnc code manually in our project. 
I added:
```
var that = this;
setInterval(function(){
        RFB.messages.fbUpdateRequest(that._sock, false, 0, 0, that._fb_width, that._fb_height);
}, 50);

```
after first fb update. But need to restart timer after receiving fbupdate from server.

I found only one client that use this optimization:
https://github.com/bgaff/vnc.js/blob/master/js/RFB.js#L164

**Comment by Ekstazi** [comment]
I think i can create PR with this optimization.

**Comment by samhed** [comment]
Having a client behaving like this can cause problems like not being able to change pixel format (since the client depends on the request mechanism to know when the server will send an update). It could also result in a clogged network if you have limited bandwidth, this could in turn give an even worse experience.

The update request mechanism exists to implement flow-control and miss-using it to work around high latency problems isn't the best way forward. The protocol has the fence and continuous updates extensions for this purpose. Do you have the possibility of using a different VNC server with more features?

**Comment by Ekstazi** [comment]
1. > Having a client behaving like this can cause problems like not being able to change pixel format (since the client depends on the request mechanism to know when the server will send an update).

    I reviewed code of tightvnc/tigervnc and turbovnc client. All set pixel format only once, when connecting. Novnc also do that immediate after clientinit.
2. >  It could also result in a clogged network if you have limited bandwidth, this could in turn give an even worse experience.
   In this case traditinal fbupdates will not give better performance
3. > The protocol has the fence and continuous updates extensions for this purpose. Do you have the possibility of using a different VNC server with more features?
    My server doesn't support fence and i can't change it.

May be we can add option for novnc to allow enable it or disable as user want ? So user can choose what method to use.

**Comment by samhed** [comment]
> I reviewed code of tightvnc/tigervnc and turbovnc client. All clients set pixel format only once, when connecting. Novnc also do that immediate after clientinit.

Yes, but it would interfere with the possibility of changing it while connected.

> In this case traditinal fbupdates will not give better performance

It would, since all the requests would be eating up bandwidth that could instead be used for updates.

> My server doesn't support fence and i can't change it. I use kvm builtin vnc.

Ok.

> May be we can add option for novnc to allow enable it or disable as user want ? So user can choose what method to use.

Maybe.. are you planning on making this feature adaptable as it was described in that paper or something simpler?

**Comment by Ekstazi** [comment]
Yes, i'll use original alghorithm for that.

**Comment by CendioOssman** [comment]
No response. Closing.
