### ISSUE TITLE
Touch device - can't send mouse scrolls to remote

### ISSUE THREAD

**Issue by juanjoDiaz** [novnc/noVNC#1267]
**Describe the bug**
Mobile scrolling doesn't seem to work (it might just not be supported).
Normal mobile scrolling (pressing and dragging) just selects text.
Choosing the wheel button from the sidebar doesn't make any difference. It stops selecting text but still it doesn't scroll.

**To Reproduce**
1. Open a noVNC connection to any VNC-enabled server
2. Open a browser and navigate to your favorite news site
3. Try to scroll down

**Expected behavior**
Ideally, I'd expect scroll to work as it would in a locally opened application.
As a minimum, choosing the scroll button of the mouse from the side menu should allow scrolling.

**Client (please complete the following information):**
 - OS: iOS
 - Browser: safari
 - Browser version: latest

**Server (please complete the following information):**
 - noVNC version: 1.1.0
 - VNC server: TigerVNC
 - WebSocket proxy: websockify

**Comment by samhed** [comment]
Yeah. noVNC doesn't have any touch gesture support at all yet.

So you're expecting that pressing and dragging one finger across the screen would send a scroll to the application? In that case, we would need that to be behind a toggle to allow for example moving a window on the remote desktop when you're expected to click and drag.

The mouse button in the sidebar toggles which mouse button is sent. When the 'wheel' button is toggled you will send a middle-mouse click - i.e. the same as when pressing (not scrolling) the scroll wheel on a physical mouse. So we would need a different toggle for these things.

Taking a step back to reflect on gestures as a whole, I think the most important actions that would feel natural to accomplish with gestures would be:

* _Send mouse scrolls_
* _Send right click_
* _Send Ctrl + Scroll_ (many applications handle this as zoom)
* _Zoom the viewport_
* _Pan the viewport_

Then comes the question what type of gesture should trigger these actions? I can see two paths here, either you try to find gestures that doesn't conflict with most common mouse actions, for example two-finger gestures:

* **Drag two fingers** to _send mouse scrolls_
* **Tap with two fingers** to _send right clicks_
* **Pinch with two fingers** to _send Ctrl + scroll_

This way you could still work as normal with one-finger press and drag allowing you to drag and drop in the remote session as normal for example.

The second path would be more in line to what you were expecting, to have gestures mimicking local applications. But in that case I see more a focus on controlling the noVNC viewport rather than sending mouse events to the remote:

* **One-finger press and drag** to _pan the viewport_
* **Pinch with two fingers** to _zoom out viewport_
* **Spread two fingers** to _zoom in viewport_
* **One-finger long-press** to _send right clicks_

Of course you can probably find some intuitive ways to combine the two paths and allow the user to choose what type of effects the gestures should have.

**Comment by juanjoDiaz** [comment]
I see. Thanks for the vert thorough overview.

Maybe I can open up a bit more on my use case.
I am trying to make some applications (web and others) accessible from a highly secured network.  Because of security considerations, it's preferable to don't send the code/binaries to the client but just send the RFB stream.
The idea was to use noVNC to stream the app window and offer an experience as native as possible (instead of, for example, RDPing to the server hosting the app and running it from there). And we would like it to be mobile-friendly. Using TightVNC remote resizing the apps seems to scale well, although the quality is a bit poor (I need to check that). The main problem is the touch gestures which are a bit counter-intuitive (or not what you would expect when opening an app on your phone).

Does RFB support sending touch events at all? Or they always have to be converted to mouse clicks?

**Comment by samhed** [comment]
I understand, thank you explaining your use case. It sounds interesting.

Touches are always converted to mouse events, the RFB protocol does not support touch events. Extending the protocol would definitely be interesting as well.

**Comment by samhed** [comment]
When it comes to sending a mouse scroll using a touch gesture, it is likely that we will do some work towards that in the upcoming months.

**Comment by juanjoDiaz** [comment]
Sounds good. I'm a consultant so I might get to help here if my customer decides to finance it 😄

Btw, this related to #944, right?
I guess that the problem is just the general lack of touch events and gesture support by RFB.

So the solution could be:
* Extending the RFB protocol
  * Do you know if this is realistic at all and what are the normal cycles for updates on the protocol and the subsequent implementation in the different VNC servers?
  * Some guys seem to have already implemented better support for mobile, but instead of contributing to RFB they created a proprietary protocol. It supports touch, multitouch, and gestures as well as sharing context like sensor data (which I'd find very useful as well).https://industry.gatech.edu/technology/mobile-mobile-remote-computing-protocol-mobile-computing-devices, http://gnan.ece.gatech.edu/archive/Uma_Peek.pdf
* Converting the touch gestures to mouse & keyboard presses
  * We have the approaches that you state above.
  * RealVNC has it's own touch modes: https://help.realvnc.com/hc/en-us/articles/360018541231-How-do-I-use-VNC-Viewer-for-Android-and-iOS-
  * Android VNC also have multiple touch modes: https://code.google.com/archive/p/android-vnc-viewer/wikis/Documentation.wiki#Input_Modes

**Comment by samhed** [comment]
> Sounds good. I'm a consultant so I might get to help here if my customer decides to finance it

Nice :wink:

#944 is about extending the RFB protocol, and I don't think we'll be going by that approach this time. It would put the touch support requirement on the server-side desktop environments and applications, and from my experience a lot of Linux software is lacking on this front still. Extending the protocol and implementing support on a VNC server would probably be more work compared to the other approach as well.

So the plan is to do this client side. Thanks for the links, those could be an inspiration :+1:

**Comment by samhed** [comment]
Fixed by #1414

**Comment by sportegioco** [comment]
I want to sincerely thank all of you for the addition of the guestures that have allowed the use of novnc in all touch devices much easier.
It would be useful to have a guesture that activates the keyboard view, or even through an icon that appears near the cursor as in the image that I am attaching.
Thanks
Gianpaolo

![guesture](https://user-images.githubusercontent.com/18140655/102280374-565dd400-3f2d-11eb-8a46-f552cc6fa0bd.jpeg)
