### ISSUE TITLE
novnc fails to load using webkit browsers and proxy middleware relying on cookies

### ISSUE THREAD

**Issue by l1ll1** [novnc/noVNC#1274]
**Describe the bug**
Not sure if this is a bug or intended behavior but:

<script type="module" crossorigin="anonymous" src="app/ui.js"></script>
in vnc.html does not transmit cookies for the origin
changing to 
<script type="module" crossorigin="use-credentials" src="app/ui.js"></script>
results in success

This is an issue because my web server is examining cookies in order to proxy the novnc connections on the the correct ssh tunnel. Without the cookie the connection is rejected.

So IMHO the bug is using anonymous rather than use-credentials within this script tag.

OTOH same origin requests should always use credentials and its not clear why script type=module should be treated as cross origin when its the same origin, so this could be a bug in webkit or a bug in firefox and chrome depending on the spec is for script type="module" (I haven't been able to find this spec)

I'm prepared to change crossorigin="anonymous" on my own installation of vnc, but I'd love to understand the choice and know what I should watch out for.

**To Reproduce**
Start a novnc server
use the server to set a cookie in the browser
open developer console in firefox and confirm that the cookie is transmitted when requesting ui.js
open the developer console in epiphany or safari and confirm that the cookie is not transmitted.

**Expected behavior**
request Cookies should be sent along with the request for ui.json

**Screenshots**
NA

**Client (please complete the following information):**

linux ubuntu 19.04 with epiphany 
mac OS X with safari 12.1.1

**Server (please complete the following information):**
- noVNC 1.1.0
- custom middle ware verifying cookies.

**Additional context**
So I'm really not sure where the bug is on this. apparently script type=module should be sent as a cross origin request even if it comes from the same origin as the rest of the script. Webkit seems to do this and performs the request anonymously. Firefox and Chrome* appear to decide that this is actually a same origin request and sends cookies, which results in success for my middleware.

Changing crossorigin="anonomous" to crossorigin="use-credentials" also results in success

Opening this bug to get a conversation going on find out what my best mitigation is.

**Comment by CendioOssman** [comment]
That sounds like a bug somewhere. This flag was changed because the browsers were defaulting to omitting credentials rather than the normal same origin policy. See these links:

https://github.com/novnc/noVNC/commit/bf82644461d95c8621923ffb472f50c1a65f9c33
https://github.com/whatwg/fetch/pull/585
https://github.com/whatwg/html/issues/2557

The browsers might have changed now so we can completely remove `crossorigin`. We will not be changing to `use-credentials` as that might cause security issues. It needs to be up to the person deploying noVNC if that flag can be used safely or not.

So I would suggest reporting the issue to WebKit, and unfortunately you'll have to modify your files until things are fixed.
