### ISSUE TITLE
Multi monitor support

### ISSUE THREAD

**Issue by samgoud** [novnc/noVNC#1287]
We are using tigervnc-1.9.0 to start vnc server and noVnc to view it on the client side in a browser. 
I have two monitors on the client side. Is there a way to move around the windows belonging to vnc session between these monitors ie say if there are two xterms inside the vnc session, can we view xterm-1 on monitor-1 and xterm-2 on monitor-2

**Comment by samhed** [comment]
Any reason you can't stretch your browser window with noVNC over the two screens?

True multi monitor awareness is not possible in web browsers however.

**Comment by pm-pm** [comment]
Maybe novnc can select (switch) between monitor 1 and 2 via menubar?

**Comment by samhed** [comment]
@pm-pm could you elaborate? Are you talking about monitor 1 and 2 of the remote or local monitors?

**Comment by samhed** [comment]
I understand what you mean, however your issue is different from what @samgoud talked about. He said he had two monitors on the client side.

**Comment by samhed** [comment]
I believe this question has been answered.

**Comment by Rayxie-cw** [comment]
the windows instlled tight vnc server and it has two monitor,then the novnc viewer display two screen with one canvas,how can I clip it to two canvas?  how do we  know it multi monitor in the novnc side？

**Comment by ghost** [comment]
> Any reason you can't stretch your browser window with noVNC over the two screens?

why would that matter if the main issue is the mouse bugging because "novnc" for example in proxmox expects one screen but gets 2, and we're getting half split working mouse while visually nothing has been changed lol? and no scaling resizing wont help in this case its completely unrelated to that, novnc must at least learn how to ignore the second screen when its not working in mirroring mode but is placed on either left or right and focus on first/primary one...

**Comment by ghost** [comment]
@samhed
