### ISSUE TITLE
How to send command key (⌘) from non-MacOS keyboards?

### ISSUE THREAD

**Issue by victorhooi** [novnc/noVNC#1342]
I'm using NoVNC as part of [Proxmox](https://www.proxmox.com/en/) - NoVNC is the main way of interacting with the VMs via the browser.

The target VM in this case is running MacOS Mojave.

The client machine (i.e. where we're accessing NoVNC) is running Linux.

Is there some way of sending the command key (⌘) easily, assuming you're not using a Apple keyboard?

I saw there was an earlier question from 2016 about remapping keys - and the answer then was it wasn't supported:

https://github.com/novnc/noVNC/issues/594

Have things changed since 2016?

Or how do people normally handle interacting with MacOS-based targets, from a non-MacOS machine?

**Comment by samhed** [comment]
Things have not changed I'm afraid.

Have you tried remapping one of your keys or adding some keybinding on your Linux machine to send the 'Meta_L' key? I think Meta is the Linux name for ⌘. Look at 'xmodmap' etc.

However, you might run into problems with the browser since browsers are kinda buggy in their keyboard handling.

**Comment by CendioOssman** [comment]
This isn't macOS specific. The command key is the same as the Windows key, or Super on Linux.

This button is now available from the control bar though, so you should be able to use things that way.
