### ISSUE TITLE
Supporting RTCDataChannel / Existing WebSocket

### ISSUE THREAD

**Issue by audiolion** [novnc/noVNC#1360]
**Is your feature request related to a problem? Please describe.**
Would noVNC be willing to accept a PR  that adds support for using existing RTCDataChannels / WebSockets when setting up the vnc client?

**Describe the solution you'd like**
The RFB constructor takes a url, but with a few modifications it could instead take an existing RTCDataChannel / WebSocket connection instead as the basis for its WebSock

I forked the code base and was able to modify the source to accept the RTCDataChannel / WebSocket and work with that. If you don't want a feature that is ok, I can use my own fork, but wanted to offer to merge it back upstream 👍

**Comment by CendioOssman** [comment]
That would be very welcome. I'm fairly sure it was already discussed on an existing issue.

**Comment by kanaka** [comment]
@audiolion This is a great idea (especially if the change is simple) but I'm curious about your use case. Are you connecting to another browser that is acting as a server (i.e. screen sharing) or is this to connect to a VNC server that uses RTCDataChannel? If it's the latter, what is the benefit over a plain WebSocket. Perhaps it's easier to setup short running sessions because you can use STUN/TURN instead of requiring manual inbound firewall tweaks?

**Comment by audiolion** [comment]
@kanaka 

> to a VNC server that uses RTCDataChannel? If it's the latter, what is the benefit over a plain WebSocket. Perhaps it's easier to setup short running sessions because you can use STUN/TURN instead of requiring manual inbound firewall tweaks?

Yes exactly, the VNC Server uses RTCDataChannel so that it can use STUN/TURN instead of manually modifying the firewall.

**Comment by CendioOssman** [comment]
Fixed via #1523.
