### ISSUE TITLE
Don't Use Certificates Stored in Web Root

### ISSUE THREAD

**Issue by ise-spolansky** [novnc/noVNC#1431]
I recently performed a security audit of a piece of software that incorporated NoVNC, and the developers of the software were unintentionally placing their certificate + private key inside the web root of the NoVNC service, meaning that anyone who could connect to the NoVNC service could just download the certificate and key. This is obviously not a bug in NoVNC since developers just shouldn't do that, but it might be a good idea to protect users from themselves anyway. This could be accomplished by either refusing to load certificates in the web root or manually 403'ing on requests to download a certificate that has been placed inside the web root.

**Comment by samhed** [comment]
noVNC doesn't include a web server. The launch script does a git checkout of our sister project websockify, that means this issue is probably better suited for that project. However, the web server included in websockify isn't suited for production environments anyway. Its ambitions are very low, to get a simple test environment up and running.
