### ISSUE TITLE
I'm not sure if this is bug (Mouse Cursor Blink)

### ISSUE THREAD

**Issue by tofutree23** [novnc/noVNC#1440]
**Describe the bug**
I am currently using noVNC as a viewer, 1.2.2.4 version of Ultra VNC as a server. 
However, on the receiving side of the share, the shareer's mouse cursor blinks as shown in the next gif file.

**To Reproduce**
Use noVNC with UVNC server

**Expected behavior**
Client can see the host's mouse cursor clearly.

**Screenshots**
![ezgif-6-7e94c95d6f93](https://user-images.githubusercontent.com/44552838/87383564-91ea2000-c5d4-11ea-80b6-036127d70f8d.gif)

**Client (please complete the following information):**
 - OS: Windows / MacOS
 - Browser: chrome
 - Browser version: 83

**Server (please complete the following information):**
 - noVNC version: recent
 - VNC server: UltraVNC 1.2.2.4
 - WebSocket proxy: DataChannel

**Additional context**

**Comment by CendioOssman** [comment]
Freaky. Not something we've heard anything about before unfortunately.

Could you test some other clients, e.g. the latest TigerVNC? It has similar cursor handling to noVNC so it would be a nice comparison.

What happens if you enable "shot dot on no cursors"? Does it still blink to no cursor, or does it start switching between the dot and the normal cursor?

**Comment by tofutree23** [comment]
First of all, 
I can see the mouse cursor on TightVNC Viewer, But in case of TigerVNC Viewer, the mouse cursor blinks in the exact same shape as noVNC.

and, I think you told me 'showDotCursor' options maybe, right?
But isn't it showDotCursor just related with client viewer options?
That mouse cursor which is blinking is presenter(from ultra vnc server)'s mouse cursor.

anyway, it happens exactly same.

**Comment by CendioOssman** [comment]
So it sounds like it could be a server bug if it happens with multiple client.

ShowDotCursor is indeed a client option. The reason I want you to try it is because its behaviour might give us a further clue if this is a server or client problem.

Could you test an older version of noVNC and see if the problem is present there as well? Please clear your browser cache between tests or things might not switch properly.

**Comment by tofutree23** [comment]
I tested from v1.0.0-beta, But was it really worked in the past? There were so many error (e.g. not defined) that I couldn't do the test.  

By the way, I'm actually using Wesock.js changed to DataChannel.js. Because of the characteristic of my project, I had to use DataChannel. So, is there a possibility that this might be involved? And are you willing to officially adopt the way you use DataChannel?

**Comment by CendioOssman** [comment]
I don't think the transport can cause an issue like this. We have an open PR for supporting DataChannel which will hopefully get finished eventually..

Have you filed a bug with UltraVNC to see what they say? Given that the issue appears in two different clients it's likely a problem in their end.

**Comment by samhed** [comment]
No response

**Comment by tofutree23** [comment]
I'm so sorry about late response.
I couldn't answer you either because UltraVNC Team didn't give me an answer, but the conclusion seems that they don't have a solution now, either. Therefore, it would be okay to close the issue.

Have a nice day.

**Comment by samhed** [comment]
Okay
