### ISSUE TITLE
Failed to start WebSockets proxy

### ISSUE THREAD

**Issue by ricardoreis** [novnc/noVNC#1443]
I had novnc installed and working normally with root.
But after stopping it, and making some user changes, I can't get it to start anymore.
I am getting the following error:

**Describe the bug**
Warning: could not find self.pem
Using installed websockify at /snap/novnc/5/usr/bin/websockify
Starting webserver and Websockets proxy on port 6081
Traceback (most recent call last):
   File "/snap/novnc/5/usr/bin/websockify", line 5, in <module>
      from pkg_resources import load_entry_point
ImportError: No module named pkg_resources
Failed to start WebSockets proxy

Could you tell me what I can do to try to correct?

**To Reproduce**
1. cd /snap/bin/
2. novnc --listen 6081 --vnc localhost:5901
3. See error

**Expected behavior**
Run novnc

**Screenshots**
1. error: https://prnt.sc/tht2sx
2. folders and files https://prnt.sc/tht3xz
3. vnc: https://prnt.sc/tht4y2
4. vncserver: https://prnt.sc/tht5md
5. Python:  https://prnt.sc/ththp9

**Client (please complete the following information):**
 - OS: Linux Ubuntu 18.04.4 LTS (Bionic Beaver) https://prnt.sc/tht6rp

**Server (please complete the following information):**
 - noVNC version: Which command to get the version? I think it's version 1.2.0. But I'm not sure.
 - VNC server: tightvncserver
 - WebSocket proxy:  I don't know, I didn't install any.

**Comment by tkedwards** [comment]
Unfortunately there have been some issues with the Snap package in the 1.2.0 release. Paths weren't set properly and there was a need to get a latest version of websockify into the snap package. I've created https://github.com/novnc/noVNC/pull/1444 to fix this, but I don't have write access so it's up to the devs here to check it and approve.

In the meantime can you revert back the snap to the previous version?

**Comment by ricardoreis** [comment]
@tkedwards Thank for your response. 

But I successfully ran novnc as follows:

`cd $HOME`
`git clone https://github.com/novnc/noVNC.git`
`cd noVNC/utils/`
`./launch.sh --vnc localhost:5901`

That way the novnc worked.

But I also find it interesting to have a snap solution.
Could you point me in the direction of how to revert back the snap to the previous version? 
I've never done this before.
 
Thank you

**Comment by tkedwards** [comment]
Use _snap revert_ to revert snap package updates. Good to hear you got it working anyway, even if not using snap.

I'm hoping the devs here will accept my pull request to fix up the snap package soon

**Comment by tkedwards** [comment]
I've added a Snap 'novnc-unofficial' to the store, so that we have a working Snap until the official one can be fixed.

The installation/use instructions are the same as already documented at https://github.com/novnc/noVNC#installation-from-snap-package, except for these slight changes:

`sudo snap install novnc-unofficial`

`novnc-unofficial --listen 6081 --vnc localhost:5901 `

`sudo snap set novnc-unofficial services.n6082.listen=6082 services.n6082.vnc=localhost:5902`

**Comment by fgadot** [comment]
> @tkedwards Thank for your response.
> 
> But I successfully ran novnc as follows:
> 
> `cd $HOME`
> `git clone https://github.com/novnc/noVNC.git`
> `cd noVNC/utils/`
> `./launch.sh --vnc localhost:5901`
> 
> That way the novnc worked.
> 
> But I also find it interesting to have a snap solution.
> Could you point me in the direction of how to revert back the snap to the previous version?
> I've never done this before.
> 
> Thank you

Same error for me, and this didn't do the trick. 
I'm stuck with 

192.168.10.120 - - [30/Sep/2020 01:40:33] 192.168.10.120: Plain non-SSL (ws://) WebSocket connection
192.168.10.120 - - [30/Sep/2020 01:40:33] 192.168.10.120: Path: '/websockify'
192.168.10.120 - - [30/Sep/2020 01:40:33] connecting to: localhost:5091
192.168.10.120 - - [30/Sep/2020 01:40:33] Failed to connect to localhost:5091

when I try to connect since last upgrade. 
No firewall on this machine. That's when I reach the WWW page and hit connect. 
Not working anymore. Any hint welcome..

**Comment by tkedwards** [comment]
BTW the official snap (snap install novnc) is fixed and available

**Comment by samhed** [comment]
It seems @ricardoreis issue is resolved. The problem you're seeing @fgadot does not seem to be the same. I suggest you open your own issue.
