### ISSUE TITLE
Is there any possible that noVNC supports flexible JPEG compression switching and quality scaling?

### ISSUE THREAD

**Issue by max-tian** [novnc/noVNC#1560]
Usually, when we use noVNC for our application automation testing,  there are lots of high quality images(JPEG) have been generated in somewhere. And then, we will use them to generate a video for issue reproducing. But, the video generation will take a lot of disk space and long time(5m). We want to compress images in order to reduce the size and time of the video. After some digging from internet, we found that JPEG has perfect compression algorithms - mozJPEG. I am wondering the work mechanism of noVNC. If noVNC can compress JPEG images when they have been captured, is there any possible we can easily configure a compression library and quality settings?

**Comment by CendioOssman** [comment]
noVNC doesn't do any compression so I'm afraid you're looking in the wrong place. It sounds like your testing system is taking the output of noVNC and creating a video stream from that. noVNC works with a HTML canvas element, so that is entirely uncompressed and doesn't have any other modes. You'll have to check your test system if there is anything that can be done there to make it go faster.
