### ISSUE TITLE
When touched with a touch screen

### ISSUE THREAD

**Issue by luoluo888** [novnc/noVNC#1642]
If you click on the same place or around the cursor when touched with a touchscreen, there is no response. The same goes for double-clicking. Can you make a touchpad mode, like guacamole. Drag to move the mouse pointer and tap to click. The click occurs at the location of the pointer.Thank you.

**Comment by freebrowser1** [comment]
The problem is that most apps (including browsers) make a mess from apps which depend on mouse input on a touch screen.

A single and double click should make no difference when using a mouse or a touch screen. That is OK.
But 'right mouse click' (context) is done by sometimes long click (Android) or two finger click, the latter not always working as both fingers should hit the screen almost within a millisecond which rarely occurs.
Dragging is sometimes done by click + hold and then moving.
Scrolling is sometimes done (preferably) by swiping one finger, but on other implementation by two fingers which is rather clunky.
It can all be made simpler, but there is no standardization for this.

The app bVNC for Android has a selection between different input methods, which is very useful.

**Comment by CendioOssman** [comment]
I'm afraid we need something more specific to work with. Yes, there are multiple ways touch gestures are mapped to mouse input. But which is best is very subjective, and we want to avoid having lots of variants that we need to maintain and clutter up things with. So if you have any specific, tangible issues, then we can have a look. Otherwise, it is just a matter of different applications will work slightly different.
