### ISSUE TITLE
novnc recording feature

### ISSUE THREAD

**Issue by OliverwengFiltered** [novnc/noVNC#1665]
I'm trying to use this recording feature. 

I'm starting the recording with the below command: 
`sudo novnc --listen 65080 --vnc localhost:5901 --record /recordings/recording.mp4` , whenever I try to connect the vnc server, it says `handler exception: [Errno 2] No such file or directory: '/recordings/recording.mp4.3`

it works if I try `sudo novnc --listen 65080 --vnc localhost:5901 ` without recording option.

any insights how to get the recording working ?

Thanks

**Comment by OliverwengFiltered** [comment]
> 

what's the recordings map that you are referring to ?

**Comment by OliverwengFiltered** [comment]
> Do you have a recordings map at the root level '/'? Make sure that the path is correct.

I did create the recordings folder at root level "/" and was expecting that by executing that command, I should be able to see some recording files be created by noVNC websockify layer, but it's throwing that error.

Any insight?

Thanks in advance.

**Comment by OliverwengFiltered** [comment]
> Do you have a recordings map at the root level '/'? Make sure that the path is correct.

Oh btw, I'm using the snap version of the noVNC, I don't know if that helps, but theoretically you should be able to reproduce the same issue by following the below steps:

1. Get a vm
2. SSH to the vm
3. Install noVNC using snap
4. Start novnc with record option
5. Connect to a vnc server.
6. The error shows

**Comment by OliverwengFiltered** [comment]
@samhed 
thanks for the info.

using github version works.

**Comment by tkedwards** [comment]
Because of Snap confinement the Snap should only be able to write to the /home/<user>/snap/novnc/current/ directory. Could you try it with having it store the recordings there? You can then move the files our to /recordings/ or wherever else.

In theory the Snap could be changed to add HOME and MEDIA 'slots', giving it access to all of your home directory as well as anything mounted under /media. However I didn't add this when creating the Snap since it doesn't seem necessary - why would novnc need to write to anywhere in your $HOME really? Violates the basic principle of not asking for permissions it doesn't need. I hope using /home/<user>/snap/novnc/current/ instead is enough for users

**Comment by OliverwengFiltered** [comment]
> Because of Snap confinement the Snap should only be able to write to the /home/username/snap/novnc/current/ directory. Could you try it with having it store the recordings there? You can then move the files our to /recordings/ or wherever else.
> 
> In theory the Snap could be changed to add HOME and MEDIA 'slots', giving it access to all of your home directory as well as anything mounted under /media. However I didn't add this when creating the Snap since it doesn't seem necessary - why would novnc need to write to anywhere in your $HOME really? Violates the basic principle of not asking for permissions it doesn't need. I hope using /home/username/snap/novnc/current/ instead is enough for users

make total sense !, thanks !

**Comment by tkedwards** [comment]
Just to add a bit of info, you could also use /home/username/snap/novnc/common instead of/as well as /home/username/snap/novnc/current/
For practical purposes of saving recordings temporarily it doesn't matter which one you use, if you're interested there's a good explanation here: https://askubuntu.com/a/762405/43371

**Comment by samhed** [comment]
Thanks for explaining @tkedwards

**Comment by Vishwamithra37** [comment]
I am having the same issue with kolla-ansible based deployment. Can anyone help?
@samhed @OliverwengFiltered  assuming you guys solved it...
![image](https://user-images.githubusercontent.com/53423141/199957818-13618b83-5975-4311-8d68-7f4bcad8e009.png)
Please do help :[

**Comment by OliverwengFiltered** [comment]
> I am having the same issue with kolla-ansible based deployment. Can anyone help? @samhed @OliverwengFiltered assuming you guys solved it... ![image](https://user-images.githubusercontent.com/53423141/199957818-13618b83-5975-4311-8d68-7f4bcad8e009.png) Please do help :[

Hi Vish, you will have to use the code base version instead of using the snap version.

**Comment by Vishwamithra37** [comment]
@OliverwengFiltered I did!, I literally downloaded the repo and replaced it onto the /usr/shar/novnc .
From what I can see, the snapcraft.yaml is in strict mode, so I am looking to make it back to classic mode.

**Comment by tkedwards** [comment]
I'm not familiar with Kolla Ansible but is there a way to have it create recordings in `/home/username/snap/novnc/current/`? That directory can be written to by the Snap, even in Strict confinement.

Pretty much all Snaps on the store will be in Strict, you have to get special approval for Classic confinement and even then users would have to install it manually with the '--classic' switch.
