### ISSUE TITLE
Use same font in noVNC1.4 as in noVNC1.3 (Clipboard)

### ISSUE THREAD

**Issue by pm-pm** [novnc/noVNC#1742]
Please use same font in noVNC1.4 as in noVNC1.3
Especially the fixed font is very useful in clipboard window! See Screenshot.

**To Reproduce**
Install noVNC1.3 and noVNC1.4beta in parrallel and put Text in Clipboardwindow

**Expected behavior**
Same font.

**Client (please complete the following information):**
Firefox 108 on Windows
![13vs14](https://user-images.githubusercontent.com/47995430/210480626-739b209c-cd1e-427f-b44e-375a13fe4c2b.png)

**Comment by CendioOssman** [comment]
I'm afraid that was on purpose to make it more consistent with the rest of the UI, and most other input fields. I understand that a fixed width font can be more useful for some input, but a variable width font is better for a lot of other input. We can't have it both ways, and we had to choose something.

So, unfortunately, this is unlikely to be changed back. Hopefully, we can improve clipboard support so that we don't need this input box at all.
