### ISSUE TITLE
Qnap noVNC throws error

### ISSUE THREAD

**Issue by subdesign** [novnc/noVNC#1879]
**Describe the bug**
When I start the Remote Desktop  (VNC) it throws the following error

**Screenshots**
<img width="908" alt="Screenshot 2024-07-21 at 7 57 36" src="https://github.com/user-attachments/assets/ade66a5a-1d3b-4c0f-a912-a0882967760d">

**Client (please complete the following information):**
 - OS: QNAP QTS 5.1.7
 - Browser: Chrome 
 - Browser 100.00

I know it's a special system, but any hint starting from the error message what could be the problem?

**Comment by CendioOssman** [comment]
Unfortunately, we have a hard time supporting custom versions of noVNC. We don't even know which version of noVNC that is based on.

That said, this error has been known to happen because of cache issues. So try clearing the browser cache and see if that makes the issue go away.

If not, then please file a bug report with QNAP.
