### ISSUE TITLE
vnc.html autoconnect option

### ISSUE THREAD

**Issue by haw3000** [novnc/noVNC#189]
Hi!
I'm using VNC_server on android and it use your novnc

one the server is started on the android mobile
I should like to connect automatically from pc

I have found that I can send in the commandline the port and the password
http://192.168.1.142:5801/?port=5901&true_color=1&password=XXX
but I'm not able to find the parameter to tell "auto_connect"
(press the button "connect" !!)
is it possible?
thank you
Stefano

**Comment by jimkring** [comment]
> This probably means you based your page on vnc.html. If you look at vnc_auto.html this is a simple variant that uses does autoconnect when the page loads. It also removes the menu which is mostly useful for before you connect anyways.

For what it's worth, `vnc_auto.html` is named `vnc_lite.html` now.

**Comment by coolaj86** [comment]
All of these are valid in the current iteration:

- <https://viewer.example.com/vnc_lite.html#/?password=supersec>
- <https://viewer.example.com/vnc_lite.html#?foo=bar&password=supersec>
- <https://viewer.example.com/vnc_lite.html?password=supersec>
- <https://viewer.example.com/vnc_lite.html?foo=bar&password=supersec>

Passwords are truncated after 8 characters because the DES key is 64 bits.
