### ISSUE TITLE
SHIFT combined keypresses sent from "software/macro keyboard" are not working

### ISSUE THREAD

**Issue by noREAVER** [novnc/noVNC#1914]
OS: Windows 10 x64
Browser: Chrome
noVNC 1.4.0-4
noVNC 1.3.0 is working though

I noticed this issue while trying to use Streamdeck to type some text to noVNC consoles in Proxmox.
noVNC is 1.4.0-0 and has the big problem of not registering anything that's supposed to be a combination with SHIFT key
Anything that's not directly sending hardware keycodes fails.
For example typing with InputStick and xKeys works fine in hardware mode.
But if I type/send text with xKeys/MacroWorks in software mode or Streamdeck, then it fails to type correctly.
*BUT* noVNC 1.3.0 (i have one installed on a ondemand instance) doesn't have this issue at all.
![image](https://github.com/user-attachments/assets/9239da68-5057-4a22-8cce-ab535b5c04ca)

Is strange that the first "<" character is typed correctly.
Also the text appears very fast, almost instantly typed on 1.3.0 but much slower and wrong on 1.4.0-4

_Originally posted by @noREAVER in https://github.com/novnc/noVNC/issues/1799#issuecomment-2490605637_

**Comment by CendioOssman** [comment]
Not sure what we changed with regard to keyboards between those two releases.

Could you enable debug logging in noVNC and see what the browser console says when you press the problematic keys. Please test both 1.3.0 and 1.4.0.

**Comment by CendioOssman** [comment]
Debug logging does not seem to be properly enabled in those dumps, unfortunately. There should be lines with "onkeyevent" in there.

Check that you don't have any filters enabled in your browser. noVNC might be logging properly, but the browser might be configured to hide those things.

**Comment by CendioOssman** [comment]
I'm afraid I don't see any noVNC issues in any of those logs. As you already noticed, noVNC is sending the correct keysyms.

Which means the bug seems to be in Proxmox somewhere. Please report the issue to them and see if they can figure out why two different behaviours are seen, with seemingly the same input.

If they find there is something we can do in our end, then please let us know. Until then, I don't see anything we can do to fix this.
