### ISSUE TITLE
Demo is Broken

### ISSUE THREAD

**Issue by josephwegner** [novnc/noVNC#278]
Seems like you've got some poorly pointed <script> tags.  I tried to fork and fix, but found myself in over my head.

**Comment by z3ntu** [comment]
bump

**Comment by DirectXMan12** [comment]
@kanaka the demo was recorded in base64 format, which won't work with the fixed playback.html.  Additionally, I think it would be better to record the demo in true color.  This poses a bit of a problem, since that gets very large, very quickly, and is not suitable for hosting in GitHub.  GitHub's GLF extension might be suitable (if you request support).  Alternatively, we could host the files somewhere else with a good cross-origin policy.  What do you think?

**Comment by kanaka** [comment]
@DirectXMan12 Updating the demo is definitely in order :-)

I've request LFS (I assume that's what you meant) for my account. We'll see how long it takes to get access. It does seem like exactly the sort of feature that would make sense for this type of data. However, I'm also fine with hosting it wherever although that probably means some small amount of monthly cost to maintain it.

**Comment by cavac** [comment]
It would also be nice to have a short documentation on how to use the record/playback feature and a way to have playback be usable in websocket mode.

For internal training purposes, i'd really like the ability to record a longer session (with my own proxy implementation) and play it back later.

**Comment by samhed** [comment]
We don't link to the demo on the website anywhere anymore. We might want to make a new one in the future, but I don't see the point in having this issue open.
