### ISSUE TITLE
noVNC fork to make it suitable for Node/browserify 

### ISSUE THREAD

**Issue by ibc** [novnc/noVNC#442]
Hi developers,

Current noVNC design is not very "friendly" in the sense that it exports really lot of stuff to `window` (for example `Utils` and lot of functions), and that is not fine when it comes to avoid namespace conflict with other JS libraries.

Even more, the library is designed in a way that it loads its dependencies (which export more and more stuff into `window`).

So I've forked it and make it suitable for Node/browserify based applications:
- https://github.com/eface2face/noVNC-node
- [API documentation](https://github.com/eface2face/noVNC-node/blob/master/docs/index.md)

As explained in the [Overview](https://github.com/eface2face/noVNC-node/blob/master/docs/Overview.md), basic features/changes are:
- Can integrate **noVNC** into a Node/browserify application.
- Don't pollute the `window` namespace. When loaded via a `<script>` tag it just exposes the `noVNC` module/Object.
- Removed all the non-library stuff (for example `include/ui.js` or `include/webutil.js`).
- Removed Flash feature.
- Removed "no native WebSocket" feature.
- Use the Node [debug](https://github.com/visionmedia/debug) library for debugging.
- Use [gulp](http://gulpjs.com/) to lint, test and build the browserified library.

This fork lacks all the utils in the "utils/" folder (it would require some effort to migrate them into the fork's design).

So, would you interested in adopting this new design? Of course what I'd love is that the **noVNC** project accepts my fork :)

**Comment by julien-f** [comment]
Good initiative!

I am using noVNC with a browserified project and it is very annoying to handle loading manually and to avoid concurrency problems.

**Comment by DirectXMan12** [comment]
I'll certainly take a look when I get some time.

You're correct in that there are really two parts to the noVNC library itself: the JS files required for a working implementation, and the JS files used by the hosting pages (e.g. `ui.js` and `webutil.js`).  Since quite a few projects embed the noVNC, I definitely think it would certainly be worthwhile to make it easier on those users.

**Comment by ibc** [comment]
Hi developers. Would you be interested in moving to my [noVNC fork](https://github.com/eface2face/noVNC-node) design so noVNC would become a library suitable for browserify/requireJS/commonJS/etc?

**Comment by samhed** [comment]
> Hi developers. Would you be interested in moving to my noVNC fork design so noVNC would become a library suitable for browserify/requireJS/commonJS/etc?

Have some patience, @DirectXMan12 said he could take a look

**Comment by DirectXMan12** [comment]
Ok, so, I *finally* got some time to take a look at this (sorry for such a delay).  I like some of the ideas (having only one top-level object with many sub-objects instead of many top-level objects, placing the "core" parts of noVNC in one directory and placing "noVNC the application" parts in another).  However, I'm not sold on using "require" -- I'd prefer to give people the option of either using something like browserify or just including the scripts using `<script>` tags.

@kanaka, @samhed, @astrand : what do you think?

**Comment by ibc** [comment]
> However, I'm not sold on using "require" -- I'd prefer to give people the option of either using something like browserify or just including the scripts using <script> tags.

The "bundle" generated by browserify is a single JS file that can be used within a `<script>` tag. It is a browserified file so:

* If the website is already using CommonJS or requireJS (AMD) it exports itself via `define` or `require`.
* If not, it exports a **single** window global `noVNC`.

So, I hope your concern is solved ;)

**Comment by kanaka** [comment]
@ibc weird, for some reason the rest of your comment isn't rendering

**Comment by ibc** [comment]
Sorry, fixed.

**Comment by DirectXMan12** [comment]
> - If the website is already using CommonJS or requireJS (AMD) it exports itself via define or require.
> - If not, it exports a single window global noVNC.

Yeah, I was more thinking of a non-minified case where someone (for their own reasons) wants to use the "normal" HTML script loading methods.  I'm not sure how applicable this is.

One other thing I was thinking about is that if we go a route like this, do we want the top-level export to be usable like so:

```js
var noVNC = require('novnc');

var client = new noVNC(target, opts);
```

I think this approach should make it easy to use.

What do other people think?

**Comment by ibc** [comment]
> Yeah, I was more thinking of a non-minified case where someone (for their own reasons) wants to use the "normal" HTML script loading methods. I'm not sure how applicable this is.

So I didn't explain well. Just take the [bundle file](https://github.com/eface2face/noVNC-node/blob/master/dist/novnc-node-0.5.1.js), put it into a normal HTML `<script>` tag and just use it (because as said before, in that case it creates `window.noVNC`):

```html
<script src="js/novnc-node-0.5.1.js"></script>

<script>
  var rfb = new noVNC.RFB(options);
</script>
```

Regarding your second concern, probably yes as the only really usable class exported by the library is `RFB`.

Said that, please also consider that the original project pollutes the `Array` class by adding custom methods to its prototype. I also fixed that. My fork does not pollute any native JS class and does not pollute the `window` namespace.

**Comment by DirectXMan12** [comment]
>Said that, please also consider that the original project pollutes the Array class by adding custom methods to its prototype. I also fixed that. My fork does not pollute any native JS class and does not pollute the window namespace.

I *think* @kanaka said there were actually performance issues with that approach, last time he tested it.  However, if/when we switch to using ArrayBuffers and typed arrays, we'll have `DataView`, which provides those methods for us.

**Comment by kanaka** [comment]
I would like to see the ability to load the original source files without any build/minification/munging script run across them first. I don't want to the any extra burden to new developers (even if small) or increase the basic development cycle time. Having a post processing step to make a smaller/single distribution object is fine, I just don't want to make it required for using/developing noVNC.

Also, my goal was that the other classes are modular enough to be used standalone. And they have been used by others in the past. For example the gtk broadway project uses the keyboard handling class without the rest of noVNC. I suspect it's been a while since they have pulled that in (but that probably because it's not as modular as it should be). Also, the websock client module is clearly separate (and is actually part of the websockify project) and there are lots of project that use the websock client together with websockify without any other parts of noVNC. If I had free time I would love to work with gtk broadway and the html5-spice guys to try and push the browser keyboard handling for this type of situation forward and have a single module that everybody uses and contributes to. But alas ...

I don't have any objections to having a single generated bundle that could be pulled in that exposes a single class as long as we don't break the above assumptions.

Regarding the Array extension, I think we just need to do a good performance test across the major browsers of alternate options. Things have changed a lot related to performance optimization of prototype chains in the past couple of years so any performance tweaks in that area may no longer be true any more.

**Comment by DirectXMan12** [comment]
> Said that, please also consider that the original project pollutes the Array class by adding custom methods to its prototype. I also fixed that. My fork does not pollute any native JS class and does not pollute the window namespace.

Agreed.  I'm thinking we'll have a preprocessor script that turns something like this:

```javascript
// requires: Input:input, Websock:websock
```

into

```javascript
var Input = require('./input');
```

To accommodate people who want to use noVNC with browserify

> Also, my goal was that the other classes are modular enough to be used standalone. And they have been used by others in the past.

Also agree here.  I think the idea solution would be flexible enough to allow the modules as separate while still easily enabling something like @ibc has.

> Regarding the Array extension, I think we just need to do a good performance test across the major browsers of alternate options. Things have changed a lot related to performance optimization of prototype chains in the past couple of years so any performance tweaks in that area may no longer be true any more.

@kanaka , do you still have the code you used to run the original tests?  I whipped up some jsperf tests, so if people could add data, that would be great: http://jsperf.com/push8-and-friends

**Comment by kanaka** [comment]
@DirectXMan12 unfortunately, I don't think I had separate tests specifically for that. The way I did performance testing was using the vnc recording and playback mechanism which we really need to get going again if we get serious about asm.js and binary arrays. I had a single recording that included several long sessions with different protocols forced in each session. The playback would report time spent rendering each protocol and also the grand total time. I would then run the playback through 10 iterations (a feature of the perftest playback page) across several different browsers to get a baseline performance. Then I would experiment with different code tweaks and after each one run the performance test to see which changes improved things across the board.

There were some surprising but consistent results that I wouldn't have predicted before hand:

* microbenchmarks frequently showed the opposite result from full playback testing (something faster in microbenchmark was slower in full playback). I don't know all the factors that contribute to this, but certainly one of the contributing factors is that garbage collection is a huge factor and it's not always obvious what will trigger GC pauses and when.

* changes often improved one protocol while slowing down another. To complicate things, this was often opposite depending on browser vendor. For example, a tweak could make hextile better but RRE worse on Chrome, while making hextile worse and RRE better on Firefox. In those cases, choosing which direction to go was often more art than science (browser popularity, likely popularity of encoding, balancing console use vs UI use, etc).

* sometimes what seemed like to silliest things would have small but non-trivial impact on performance and often only in one browser or opposite in different browsers (things like using "var func = function()" vs "function func()")

* not everything that seems like it should be an obvious speedup ends up actually improving things. I did test switching a good portion of the code to use binary arrays at one point back when typed arrays was just starting to be implemented in browsers. I discovered after conversion that the playback was actually significantly slower. At that point I wrote some microbenchmarks to test the code and discovered that in fact, typed arrays were generally slower. In fact, I just realized I did a blog post on that very topic: http://blog.n01se.net/blog-n01se-net-p-248.html (apologies for the awful background). I think it was just the case of regular arrays having more than a decade of performance optimizations (especially around GC). So hopefully that is no longer the case but I haven't done an update to that testing. I do strongly suspect that asm.js plus binary arrays will give us a huge speedup but we'll still want good testing to be sure.

**Comment by ibc** [comment]
Guys, I just cannot agree with the rationale given above. If some people just use a "component" of noVNC then may be the project should be **properly** splitted into multiple specific libraries. That's hard given that the project includes its own "logger" and helpers for Cookies!

IMHO you are discarding a great solution without properly understanding what I mean. For example: let's suppose noVNC can be splitted into tree libraries A.js, B.js and C.js.

All those libraries can be done in a modern way, coded as in Node, and having all of the a browserified version for standalone usage in the browser via legacy `<script>` tag. And then, if somebody needs A, B and C, then he can add those dependencies to its Node/browserify project and generate a final bundle/app, or can take all the bundled/browserified files of A, B and C and append them into `<script>` tags separately, since A would expose `window.A`, B would expose `window.B`, etc etc.

If you want an example, check JsSIP which uses rtcninja as dependency, but at the same time rtcninja can be used standalone (see its `dist/` folder for the bundled file). And at the same time, JsSIP can be integrated into a Node/browserify project via package.json, etc etc.

* https://github.com/versatica/JsSIP
* https://github.com/eface2face/rtcninja.js

I just can't buy any of the replied rationale. If you just prefer legacy / old-fashion `<script>` for ever and ever, ok, let's finish this thread then. But I hope you understand that with my proposal you **still** can do that ;)

**Comment by DirectXMan12** [comment]
> given that the project includes its own "logger"

I actually somewhat agree with this --the "logging" functions are really just a wrapper around console.log and friends -- they just skip calls to certain functions dpending on the enabled log level.  I'd have to check the performance impact, but it may be worth getting rid of the separate logging functions and just using `console.xyz` directly.  This would certainly help making the libraries separable.

> and helpers for cookies

The cookie helpers are just in `ui.js` and are only used in vnc.html and vnc_auto.html -- they are not used at all in the "core" noVNC libraries.

I'm currently working on tests for a couple of major patches, but I'll take a stab at producing a PoC after that, and we'll go from there.

**Comment by ibc** [comment]
> I actually somewhat agree with this --the "logging" functions are really just a wrapper around console.log and friends -- they just skip calls to certain functions dpending on the enabled log level. I'd have to check the performance impact, but it may be worth getting rid of the separate logging functions and just using console.xyz directly. This would certainly help making the libraries separable.

**Comment by ibc** [comment]
> it may be worth getting rid of the separate logging functions and just using console.xyz directly. This would certainly help making the libraries separable.

Why console? So if somebody wants to remove all those logs it should mangle the library. There is a much modern solution which I've incorporated in my [noNVC fork](https://github.com/eface2face/noVNC-node): the Node [debug](https://github.com/visionmedia/debug) module, which can be enabled or not as the developer decides.

> I'm currently working on tests for a couple of major patches, but I'll take a stab at producing a PoC after that, and we'll go from there.

That's fine, but I wonder why don't you check my fork given that it satisfies all the requirements exposed in the description of this issue. Any other approach will probaby:

* Pollute window namespace.
* Be non AMD/requireJS/browserify friendly.
* Pollute Array prototype.
* Will log, yes or yes, to console.

**Comment by kanaka** [comment]
@ibc sorry, I personally don't have time at the moment to invest in detailed evaluation of the changes you made in your repository (family, day job and PhD are priority for me these days and suck up almost all my free time). One of the issues for me personally is that the way you did the fork puts a big onus on me/us (and therefore a lot of extra time) to figure out what it was you've changed and how the changes relate together. It would help greatly if this was an actual github fork with the different logical changes separated into separate commits so that the changes could be diff'd more easily and evaluated and/or merged on a case-by-case basis. Just as a personal example for how things work for me right now, a lot of my free time lately tends to come in small chunks and during times when I only have my phone. If there were a pull request with multiple commits separated into logical changesets then I could evaluate them on my phone as I have the time. Anyways, I'm sure you are quite busy too so I have no idea if you have the time or motivation to do that, but just a thought...

@DirectXMan12 some of the reason for the abstraction around logging has gone away, e.g. when this was originally created, not all browsers had console.{log,warn,error}. The checks for debug level do obviously have a performance impact (which is why most fast path logging is actually commented out). But a MUCH bigger effect is the impact from the browsers actually writing the log messages. In particular firefox used to be really pessimal if you were doing a lot of console logging. So you don't want to be logging much by default, but it is definitely convenient to have a query parameter method of turning it on. Comes in particular handy when someone runs into weird issues and we can just ask them to replicate in the current version they are using but with logging enabled and then paste the output (e.g. follow this page: https://github.com/kanaka/noVNC/wiki/Troubleshooting). I have no objection to simplifying the logging (to cleanup any namespace pollution for example and remove the cross-browser noise that's no longer relevant), but I think it's good to keep it configurable and have the code delivered in production but disabled (i.e. not something that is added by a debug build phase).

**Comment by DirectXMan12** [comment]
> That's fine, but I wonder why don't you check my fork given that it satisfies all the requirements exposed in the description of this issue. Any other approach will probably

@ibc: I did check your fork.  We've had several changes since then, so at the very least, I need to do what you did to your fork to the current codebase.  Additionally, I need to figure out a way to retain the "application" part of the code in the repository, and things like that.

> Why console? So if somebody wants to remove all those logs it should mangle the library. There is a much modern solution which I've incorporated in my noNVC fork: the Node debug module, which can be enabled or not as the developer decides.

Again, I'd have to evaluate the performance impact -- it might not be much of an impact in your use cases, but there are several bits of code need to support *really* high throughput.

**Comment by VoidVolker** [comment]
I'm voting for one hi-level function fro exports as general solution - it is much more usable. As additional solution just add some build script to include or not include some modules/components. 
Currently, I want to use novnc as one of components with custom UI and features. And it be more usable to use it like this:

    var vnc = new noVNC({ canvas: myCanvas [, more_default_options] });
    vnc.connect({ host: 'a', port: 1, password: 'p' [, canvas: otherCanvas, more_not_default_options] });

Currently I'm loading noVNC in iframe and it is not very usable.

**Comment by 131** [comment]
There is no "nice an easy" switch from a plain old project to an ES6 module / browserify design.

I feel like@DirectXMan12 branch is a dead end, nothing ES6 compliant/browserifiable)
I stick with @ibc fork (as i'm finding what i'm searching in it). So if that is okay, i'll :

* I'll sync noVNC master
* for efficiency, as websocket are able to transport binary data, I'll try to drop websock (maybe i'll find something i'm missing, but for now, i know they can - as [we can transport raw h264 video feed](https://github.com/131/h264-live-player) )
* for simplicity, i'll ditch gulp * and just use a npm task for dist
* (maybe) I'll switch to ES6 classes and toggle (maybe) babelify transform in the npm run dist task
* i'll swith tab to spaces
* i'll use submodule (moutjs, base64, des) to replace utils (and therefore add dependecy)
* Using submodule when possible will make code coverage (through istanbul) relevant
* debug is a bless (as it is defined on 'compile time' - through browserify opts ), console.log is a pain.
* i'll ditch the /dist folder for a /demo folder (as github says i should)

# About submodules
* Using submodule when possible will make code coverage (through istanbul) relevant

* May i remind to everyone that require() can include a specify file of a submodule ?
require('mout/object/default') is a drop-in replacement for util.set_defaults, expect that it's fully tested, and maintened. (see lodash, mout, async design)


# About merging
@kanaka, there is _no_ _sane_  _way_ to merge this kind of fork. If you are enclined to take a look/change your mind, may i suggest you to take @ibc files , compare them file by file with the master one (for the /include/ dir, of course). And if you like what you are seeing, just use them (no commit/branch/commit from @ibc fork will ever be relevant in your history). For the most part, git handle file renaming not so bad, and that's okay.

=> This is not the kind of branch/refactoring github help us working efficienlty with.

**Comment by olivierlambert** [comment]
@131 If you can start by sync the @ibc fork to current master of this repo, I'll be **very happy**. I would really need to test the recent changes to support non-English layouts for QEMU.

Is it something doable in a matter of days/weeks or months?

**Comment by 131** [comment]
days, i guess, i think i'll have this done before monday.

**Comment by olivierlambert** [comment]
:tada: :tada: :tada: :tada: :tada: 

How do you want to proceed: sending a PR to @ibc repo? We should ask him to add some maintainers to it, until someone decide (ideally) to merge into a single mainline solution (ie: here) :+1:

**Comment by fufroma** [comment]
@131 Hello, any news about this? :smile:

**Comment by 131** [comment]
@DirectXMan12  end up merging a (kinda) half way solution. On my side, my deadline got postponed, so for now, i have no urge in this.
I've setup a fork for the time being https://github.com/131/noVNC2

**Comment by fufroma** [comment]
@131 Ok, i'll keep an eye on your fork! Hope you'll be able to make us happy :smile: !

**Comment by shaneharris** [comment]
https://github.com/novnc/noVNC/pull/496 is this solved ?

>To reiterate, the tool to build browserify- and/or ES6-compatible files is utils/use_require.js. When called on its own, it will generate ES6-compatible files (from core/) into lib/. Things get a bit funky with Pako (since it's a CommonJS module), but that's left as an exercise to the reader. When run with --as-require, it will instead generate CommonJS/browserify-compatible files (Pako works fine here) into lib/ (from core/). Finally, when run with the -b option, it will generate a fully-bundled app including vnc.html and all the app UI and whatnot. This is mainly intended as an example, but can also be used as a convenient way to deploy a bundled copy of noVNC.

**Comment by DirectXMan12** [comment]
It's was solved more recently as well with the move to ES6 modules.  Nothing's been officially published on NPM, but the `./use_require.js` tool is still what you want.  You can now generate as CommonJS, or use the ES6 modules as part of your build if you are already using Babel yourself.

**Comment by CendioOssman** [comment]
@DirectXMan12, any reason to keep this issue open? It seems like we have this feature now.

**Comment by DirectXMan12** [comment]
I was keeping it open until we actually published on NPM, but since that'll be shortly (and it's usable from GitHub pretty easily), I think we can close this.
