### ISSUE TITLE
RealVNC encryption always on - Unsupported auth scheme 5

### ISSUE THREAD

**Issue by yarontorbaty** [novnc/noVNC#593]
noVNC version 0.5.1 on Ubuntu 14.04 LTS
Client: Windows/Chrome Browser 49.0.2623.110m
Issue:
Trying to connect to a RealVNC server which has encryption "always on" enabled, getting the following error:
Unsupported auth scheme 5

Created SSL certificate and used encrypted=true on connection params - same issue.

**Comment by DirectXMan12** [comment]
Sorry for the delay here.  I'm not sure how much we can do about this.  As far as I can tell, there's not much documentation on the actual protocol for RA2, and I don't really have time to try and reverse-engineer it, either.  Furthermore, supporting end-to-end encryption in noVNC is a bit difficult (except when it's just using WSS on a VNC server that supports WebSockets natively), since doing crypto is JS is difficult.  It *might* be possible using the WebCrypto API (https://developer.mozilla.org/en-US/docs/Web/API/SubtleCrypto).

I'd be willing to look at a patch, but I don't really have the time to do it myself, at the moment.

If you need encryption on your connection, I'd recommend setting up WSS (SSL) between your browser and the WebSocket proxy, and then security the connection between the WebSocket proxy and the VNC server.  If you need authentication, I'd recommend setting it up during the HTTP negotiation phase as the client tries to connect to the proxy.

**Comment by samhed** [comment]
I don't think its feasible to have issues open for all RealVNC incompabilities. Closing this.

**Comment by jsrober** [comment]
UltraVNC is able to connect to RealVNC Enterprise 6.3.2, but noVNC displays "Unsupported auth scheme: 13". Do you know what we can change in noVNC to allow it to connect to RealVNC Enterprise 6.3.2?

Thanks,
John

**Comment by jsrober** [comment]
Hi @samhed . Thanks for responding. I guess I figured since UltraVNC could figure out the undocumented RealVNC protocol, that we could do the same. Unfortunately I'm not experienced in this so thus far I'm not much help. I've been studying the auth code in rfb.js, but I don't have a solution.

**Comment by jsrober** [comment]
Hi @samhed 

noVNC branch stable/v0.6 does NOT work with RealVNC. I get the auth error we discussed above.

noVNC master DOES work with RealVNC!

This is great! I'm happy that noVNC can work. The only problem is that the scrollbars don't show up. I'm not sure why. Any ideas?

**Comment by samhed** [comment]
That's good to hear.

With regards to the scrollbars, could you open a new issue please?
