### ISSUE TITLE
Copyright format at the top of files

### ISSUE THREAD

**Issue by samhed** [novnc/noVNC#674]
As brought up by @DirectXMan12:

Currently we have a list at the top of each file listing contributors each on a separate line. These lists are currently quite incomplete and this style won't work well as the lists grow.

Suggestions? Thoughts @kanaka?

**Comment by samhed** [comment]
Suggested by @DirectXMan12 in @653:

> Copyright (C) the noVNC authors and then have an authors file elsewhere?

**Comment by kanaka** [comment]
I like that plan. In terms of author list we could just expand/complete the last section of the README. If we go with a separate authors file then we should change the README to refer to it (so we just have one copy). I would probably lean slightly towards just updating the README since that's a bit more prominent (and the number of major authors is fairly small). However, I don't have strong feelings about it so I'll go along with whatever the the person who actually does the work decides to do :-)

**Comment by DirectXMan12** [comment]
A separate authors file can be nice if the list ever grows longer.  Either way works for me, though

**Comment by DirectXMan12** [comment]
I'll put up a PR, since I've got a few minutes now :-)
