### ISSUE TITLE
Please upgrade noVNC on novnc.com

### ISSUE THREAD

**Issue by patrakov** [novnc/noVNC#722]
http://novnc.com/ features a really old version of noVNC, before the redesign with a sidebar. Please upgrade it.

**Comment by samhed** [comment]
As far as I know, @kanaka is the one with access to that server

**Comment by DirectXMan12** [comment]
With the new org, I should have access, IIRC.  I'll see what I can do.

**Comment by kanaka** [comment]
@DirectXMan12 the gh-pages branch is currently just an index.html file that redirects to http://noVNC.com/noVNC/vnc.html where noVNC/ is just a git submodule that points to the master branch (just a really old version). Note that the forwarding keeps query and hash parameters. So just updating that submodule will probably do the trick. This structure allows the gh-pages branch to basically just contain the website stuff and use the master branch for the actual app. It has the downside of using a redirect.

One thing that got dropped from vnc.html (f9fff03719de1d1410a69803a383a267fbd7e503) was the description popup which would detect when somebody was using online app and display a informational popup. We might want to restore something like that so that people who land there have some info/links for where to find more info. Another option would be to make index.html actually have content with very obvious link to the app. I think it's good to have a short URL for loading the app (note above that the redirect retains query/hash params if JS is enabled) and it's also the behavior that has been there for a few years now. But I could probably be convinced otherwise by a good counterargument. :-)

**Comment by samhed** [comment]
> Another option would be to make index.html actually have content with very obvious link to the app.

I personally think that this is better than having specific code for one hosting location

**Comment by kanaka** [comment]
@samhed one option that might be interesting to consider is to have small JavaScript onload routine on the info page that checks if there are query parameters (perhaps checking if they match a certain set) and in that case redirecting to vnc.html retaining those parameters. That would probably prevent breakages for people that are currently using noVNC as parameterized app. It would be pretty trivial to add (index.html currently has the redirect code).

**Comment by samhed** [comment]
I like that idea!

**Comment by samhed** [comment]
I've now updated [novnc.com](http://novnc.com) to go to the info page unless query parameters are provided, in that case it will still redirect to the app.

So you can still for example use [novnc.com?host=my.server.com](http://novnc.com?host=my.server.com)

The app on novnc.com/noVNC/vnc.html is the latest release, however since it was quite a while since our latest release, you might want to use a newer version, in that case go to:

http://novnc.com/noVNC-latest/vnc.html

Once 0.7.0 has been released, we will update novnc.com/noVNC/vnc.html again.
