### ISSUE TITLE
no keyboard input

### ISSUE THREAD

**Issue by LocusSolusWired** [novnc/noVNC#739]
Hello, 

At the moment of posting this issue:
git pull: Already up-to-date.

Keyboard input does not work at all. Mouse inputs are ok tho.
host debian stretch, qemu from repository
guest: windows 7 32bits

keyboard input does not work on those browsers:
chrome 55.0.2883.87 (64-bit)
firefox 45.6.0 (64 bit)

Openning the browsers console shows no errors at all.

I tested on Konqueror 4.14.25 under KDE 4.14.26, the keyboard input work just fine, but then I lost the mouse tracking position.

Keyboard and mouse works just fine using remote-viewer 5.0

**Comment by LocusSolusWired** [comment]
@samhed , Hello - Yes I tried the following:
-k pt-br ( my default settings)
-k en-us
and no '-k keymap'

None of the above worked in chrome 55.0.2883.87 (64-bit) and firefox 45.6.0 (64 bit).

But those qemu settings worked using Konqueror 4.14.25 under KDE 4.14.26. In Konqueror, after passing '-k pt-br', key combinations like those "é" , "ç", "á" worked just fine.

Still, I have to try on some IE or older Firefox - I am working on that.

**Comment by samhed** [comment]
Did you get an opportunity to test other browsers?

**Comment by feO2x** [comment]
First of all, thanks for this awesome product!

Unfortunately, we have the same problem here: since v0.6.1 keyboard events are not transmitted so that XenServer can interpret them properly. We are aware that [XenServer starts Qemu with the `-k en-us` parameter](https://bugs.xenserver.org/browse/XSO-650).

We tested Chrome 55.0.2883.87 m, Firefox 50.1.0, and IE11, all with the same result: up to v0.6.0, keyboard events are transmitted fine, and since v0.6.1, the keyboard stops working. This is a different behavior than https://github.com/novnc/noVNC/issues/680.

Should we stick with v0.6.0 and wait for the v0.7 release that might fix this problem? Or is it more appropriate to try to exchange the `KeyboardUtil.QEMUKeyEventDecoder` with the `KeyboardUtil.KeyEventDecoder` to get the old style of transmitting key events?

**Comment by oglueck** [comment]
Extra annoying: to get correct keyboard behaviour with any standalone VNC client you need -k. But then noVNC breaks completely and you lose all keyboard input. So I have to decide which use case to break when I startup qemu.

**Comment by samhed** [comment]
Does #766 make any difference for you guys? @feO2x @oglueck 

@LocusSolusWired are you still around?

**Comment by oglueck** [comment]
Yes #766 fixes it completely. I simply tested CendioOssman:keyboard and it works correctly with both native VNC and noVNC and qemu with -k de-ch. @samhed

**Comment by samhed** [comment]
@oglueck good to hear!

**Comment by CendioOssman** [comment]
#766 is merged so this is now fixed.
