### ISSUE TITLE
Is noVNC compatible with regular VNC viewers such as xvncviewer?

### ISSUE THREAD

**Issue by adrelanos** [novnc/noVNC#741]
Is noVNC compatible with regular VNC viewers such as xvncviewer?

**Comment by samhed** [comment]
I'm not sure what you are asking here.. noVNC is a VNC viewer which follows the RFB protocol.

**Comment by adrelanos** [comment]
I have noVNC seen started like this.

    websockify -D --ssl-target --web /usr/share/novnc/ 5900 -- x11vnc -forever -shared -find -unixpw -avahi -loop

Then noVNC is reachable in the browser on port 5900. However, I wasn't able to connect to the same port using xvncviewer.

Can noVNC (by browser) and a regular VNC (x11vnc / xvncviewer) be reachable on the same port?

**Comment by kanaka** [comment]
@adrelanos you'll need to start x11vnc separate from websockify and then use websockify to forward to the x11vnc port rather than using websockify to start up the application directly like that. When you start the application like that, websockify moves the actual application port to a random high port and then forwards to it.

```
x11vnc -forever -shared -find -unixpw -avahi -loop
websockify -D --ssl-target --web /usr/share/novnc/ 6900 5900
```

Then you can attach xvncviewer to port 5900 and noVNC to port 6900.

Alternatively, libvncserver (x11vnc) has had direct support for websockets for a while. And that can work on the same port as the VNC service and you don't need websockify for it. So you might want to look into that.
