### ISSUE TITLE
Mobile device RFB data not rendering properly  

### ISSUE THREAD

**Issue by vgokul129** [novnc/noVNC#783]
I tried noVNC on mobile device where my mobile resolution is 640 * 480 (which is smaller than my RFB data 1280 * 720 sized from server). I got only small portion visible on my mobile device. When attempted to scroll my canvas(by enabling drag viewPort), i was able to scroll but the canvas is not updated with the interested data. How can i get the frame updated instantly when scroll around my canvas ?

**Comment by samhed** [comment]
This should work, what version of noVNC are you running? What kind of device are you running into problems with? With what browser?

Could you show a screenshot?

**Comment by vgokul129** [comment]
I tried with this [link](http://novnc.com/noVNC/vnc.html). I have attached the screenshot of my trials. 

Screenshot of PC FireFox Browser, which seemed working fine.

![pc-ss](https://cloud.githubusercontent.com/assets/8913459/23690885/ebd065b6-03ea-11e7-8752-d4c59f63aaf4.png)

When the same i tried on Lenovo Tab 2 A7-30HC model Android device

![mobile-ss1](https://cloud.githubusercontent.com/assets/8913459/23690867/ce90f132-03ea-11e7-851c-48c86b3cb51b.png)

When tried dragging got the issue:

![mobile-ss2](https://cloud.githubusercontent.com/assets/8913459/23690876/dfed7ce8-03ea-11e7-884e-1ee74ea14c00.png)

Please find the white patch of missing frame region.

**Comment by samhed** [comment]
Ok, thanks for clarifying and for the screenshots.

novnc.com is running the latest release, and this is a known issue ( #517 ) that has been fixed since then. We did however not finish a new release yet. But if you want to try a bit newer code, you can try it here:

http://novnc.com/noVNC-latest/vnc.html

PS: I suspect that you will run into the same problem if you enable clipping and make the browser windows smaller in Firefox on your PC.
