### ISSUE TITLE
module loader doesn't work on Safari 9

### ISSUE THREAD

**Issue by CendioOssman** [novnc/noVNC#815]
We have an old iPad here that's still on iOS 9.3.5. The module loader fails to work here with this error:

```
[Error] SyntaxError: Strict mode does not allow function declarations in a lexically nested statement.
	(anonymous function) (browser-es-module-loader.js:1172)
```

**Comment by CendioOssman** [comment]
There's also a lot of `const` and `let` it gets upset about.

**Comment by samhed** [comment]
Safari 9 isn't that old. iOS 9 was released September 16, 2015 and 9.3.5 was released August 25, 2016. It looks like iOS 9 still holds a ~13% market share among iOS users. And some devices can't be updated to iOS 10.

**Comment by CendioOssman** [comment]
Two options in that case, ban all use of `const` and `let`, or employ babel for this.

And I guess we need to look at this before release?

**Comment by samhed** [comment]
Yeah, I don't know. @DirectXMan12 any thoughts?

**Comment by DirectXMan12** [comment]
> It looks like iOS 9 still holds a ~13% market share among iOS users. And some devices can't be updated to iOS 10.

gah, I hate that Apple doesn't update Safari properly on iOS devices >:-(.  It's probably better to just fix it without Babel.  I think, ideally, I'd like to avoid using Babel for anything but the ES6 modules stuff.  The `const` declarations should be a fairly straightforward find-replace fix.  `let` *might* be a bit more complicated, but shouldn't be too bad.  Function declaration shouldn't be too bad either -- should just be changing `function foo` to `var foo = function`.

**Comment by CendioOssman** [comment]
Any easy way we can test for this so people don't screw this up again by accident?

**Comment by DirectXMan12** [comment]
I *think* Sauce supports testing on mobile browsers, so we might just be able to add it to our browser matrix.

Also of importance: what's the threshold for removing support for a browser version?

**Comment by kanaka** [comment]
@DirectXMan12 my personal rule of thumb historically was to try and support at least 90-95% of browsers currently in-use according to caniuse.com/StatCounter. So basically my policy was that I would drop the most hard to support browsers as long as doing so didn't drop supported market share supported below 90%. Although to be completely honest, I didn't include IE 6-8 in that calculation for obvious reasons. That's still probably a fairly reasonable goal, however, if we set a more concrete policy that should probably be worked out between you (representing OpenStack) and the Cendio team. It may be that a typical OpenStack and ThinLinc user is more likely to be using up-to-date browsers in which case the global StatCounter data might not be as relevant.

Safari on iOS used to be so nice. Now it has become the new IE 6. I.e. a new dominant player that pushed the web forward initially (in order to gain marketshare) but would now prefer that people didn't actually use the web anymore. :-(

**Comment by kanaka** [comment]
BTW, there is apparently a "nomodule" attribute that can be included in script tags and browsers that support es6 modules should ignore script tags so marked: https://jakearchibald.com/2017/es-modules-in-browsers/ Unfortunately, it looks like browser support is spotty so it probably won't help us even though it's what we probably want :-(
