### ISSUE TITLE
increase log level

### ISSUE THREAD

**Issue by bforpc** [novnc/noVNC#844]
Hi folks,

because i didnt find a solution for my "noVNC behind apache proxy" problem, 
my question is:  how can i increase the log level of the noVNC launcher, to see whats going on of the not working connection.

Bfo

**Comment by bforpc** [comment]
After finding a litte more info with console logging, i got these errors:

rfb.js:397 connecting to wss://192.168.5.208:6080/websockify
/nv/core/websock.js!transpiled:231 WebSocket connection to 'wss://192.168.5.208:6080/websockify' failed: Error in connection establishment: net::ERR_CONNECTION_RESET
open @ /nv/core/websock.js!transpiled:231
/nv/core/rfb.js!transpiled:213 WebSocket on-error event
(anonymous) @ /nv/core/rfb.js!transpiled:213
/nv/core/rfb.js!transpiled:182 WebSocket on-close event
(anonymous) @ /nv/core/rfb.js!transpiled:182
/nv/core/rfb.js!transpiled:605 Failed when connecting: Failed to connect to server ( (code: 1006))
_fail @ /nv/core/rfb.js!transpiled:605


bfo

**Comment by bforpc** [comment]
After testing and testing and testing ... i found out, that noVNC is working well with self signed certs. If i use letsencrypt fullchain.pem, it doesent. So the question is: How can i secure noVNC with a letsencrypt cert? Everything else then noVNC, like apache2 and postfix are running very well with the letsencrypt cert.
The Letsencrypt fullchain.pem is the combined cert with key and cert together,

bfo

**Comment by kanaka** [comment]
@bforpc can you file a bug against the websockify project for the letsencrypt problem? This is the noVNC project and the problem you described is not a problem in noVNC. Also, the letsencrypt problem sounds like one that deserves it's own bug so that others who run into this later can more easily find the answer. In that new bug can you please specify how you are starting websockify and what the result is (it's not clear if your letsencrypt issue is the same one as your originally encountered).
