### ISSUE TITLE
Could not work with realvnc?

### ISSUE THREAD

**Issue by howknows** [novnc/noVNC#940]
Hi all,
When I using realvnc Python sdk ,and run it's sample basicServerPython.py listening  5900 port on my local machine. And I use noVNC connect to localhost:5900(the realvnc server). But I got error on my chrome console:
`rfb.js:573 Failed when connecting: Unsupported server (Unsupported security types: 13,133,5,129,192)

_fail @ rfb.js:573

_negotiate_security @ rfb.js:800

_init_msg @ rfb.js:1155

_handle_message @ rfb.js:639

_recv_message @ websock.js:311
`
Is the noVNC not support realvnc server, or something else?

**Comment by samhed** [comment]
RealVNC does not share their current protocol with the world. This makes it difficult for open source projects like noVNC to support this server.

**Comment by DirectXMan12** [comment]
To elaborate a bit more, RealVNC uses several custom security types, and it's not clear how some of those are implemented.  For others, the implementation is known, but is difficult in the browser.  If you're only going to be using the server with noVNC, you can use external forms of authentication (bearer tokens, for instance) on your websocket connection, and use WSS (SSL for websockets) instead of relying on any form of VNC authentication and security
