### ISSUE TITLE
Please document how to compile better

### ISSUE THREAD

**Issue by agronick** [novnc/noVNC#966]
I spent a few hours searching around the codebase and docs until I found this post #945 explaining how to compile the project.

There is the file docs/notes that looks like it might be obsolete saying to use browserify. I couldn't find anything in docs or the readme regarding use_require.js.

I think something that says run
`npm install <project dir>`
Folowed by
`utils/use_require.js --as <format>`
would be helpful to a lot of people.

**Comment by samhed** [comment]
the wiki is editable by anyone :)

And just to clarify here, you don't have to do this. noVNC will work with the module system in very new versions of Chrome, Safari and Edge, but the slow fallback version is still used in older browsers and Firefox. But in production it's recommended that you instead make use of use_require.js due to the lack of full support across the browser platforms at the moment.

**Comment by agronick** [comment]
I know. It was more of a personal preference and to go along with the rest of the codebase. Awesome tool by the way. It really helps us a lot.

**Comment by agronick** [comment]
I added it to the wiki: https://github.com/novnc/noVNC/wiki/Integration

**Comment by CendioOssman** [comment]
I've added upon that documentation and put it in the repo so that it matches the code. Please check the README for links.
